This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./tfgtfmthesisuam.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file tfgtfmthesisuam.acn....done (97 entries accepted, 0 rejected).
Sorting entries....done (712 comparisons).
Generating output file tfgtfmthesisuam.acr....done (76 lines written, 0 warnings).
Output written in tfgtfmthesisuam.acr.
Transcript written in tfgtfmthesisuam.alg.
